
myexe: myStrFunc.o myMathFunc.o myMain.o
	gcc -o myexe myMain.o myStrFunc.o myMathFunc.o 

myStrFunc.o: myStrFunc.c
	gcc -c myStrFunc.c

myMathFunc.o: myMathFunc.c
	gcc -c myMathFunc.c

myMain.o: myMain.c
	gcc -c myMain.c
